name: Laravel CI


on:
   push:
      branches:
         - main
jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Repository yuklash
        uses: actions/checkout@v4


      - name: PHP o'rnatish
        uses: shivammathur/setup-php@v2
        with:
            php-version: 8.3

      - name: PHP versiyasini tekshirish
        run: php -v


      - name: Composer versiyasini tekshirish
        run: composer --version

      - name: Composer install
        run: composer install --no-interaction --prefer-dist

      - name: Docker build test
        run: docker build -t laravel-devops-lab .

      - name: Secret test
        run: echo "${{ secrets.TEST_SECRET }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
           docker tag laravel-devops-lab developer01242757/laravel-devops-lab:latest
           docker tag laravel-devops-lab developer01242757/laravel-devops-lab:v1

           docker push developer01242757/laravel-devops-lab:latest
           docker push developer01242757/laravel-devops-lab:v1

       - name: Deploy
         run: |
            cd /home/admin0124/Project-test/docker-project
            docker compose pull
            docker compose up -d
